### ISSUE TITLE
Wrong colors applied after last changes in bootstrap-italia

### ISSUE THREAD

**Issue by PiemP** [italia/bootstrap-italia-playground#27]
In this commit https://github.com/italia/bootstrap-italia/commit/f2aac219b2bf8c90086669a308b486ab92b49695 (seems related to this PR italia/bootstrap-italia#776) the file `colors_vars.scss` is changed by removing the use of the variables $primary-h, $primary-s, $primary-b in the $primary calculation. 

The result is: 
![playground mmmm](https://user-images.githubusercontent.com/2736009/215442855-6c5a6bbf-dfb5-48ca-b05a-3f961fcadf35.png)

In this image can see blue colors in the header. The footer have the same problem. I have to understand the ratio of the commit cited to eventually do a PR.

**Comment by mariantanase** [comment]
Confermo

**Comment by 222dipa** [comment]
Confermo, anche io ottengo la stessa cosa!

**Comment by zetareticoli** [comment]
We're working on a fix. More info to come.

**Comment by zetareticoli** [comment]
The fix is live in [v2.3.4](https://github.com/italia/bootstrap-italia/releases/tag/v2.3.4)

We've restored the three `$primary` variables in HSB format: `$primary-h` `$primary-s` `$primary-b`.

You can customize the **primary color** (aka theme color) as did in the past.

But, in [v2.3.0](https://github.com/italia/bootstrap-italia/releases/tag/v2.3.0) we've also introduced new semantic variables (linked to next design tokens integration). 

These variables are:
```scss
$color-background-primary-lighter
$color-text-primary-active
$color-text-primary-hover
```

They're set in `_colors_vars.scss` ([from line 392](https://github.com/italia/bootstrap-italia/blob/main/src/scss/utilities/colors_vars.scss)) and referenced in `bootstrap-italia-comuni.scss` for override [(lines 26-28)](https://github.com/italia/bootstrap-italia/blob/main/src/scss/bootstrap-italia-comuni.scss)

Some components now uses these variables instead of the old ones (like `$neutral-` or `complementary-`).

In order to correctly theme your BI installation, you should assign a value to theme. You could use HEX, HSL or HSB values.

**Comment by astagi** [comment]
@PiemP I think we can close this issue, I'll update README accordingly.

**Comment by PiemP** [comment]
I keep my eyes on you @astagi 👀😂 ... please document it ... TY

**Comment by PiemP** [comment]
thank you @astagi

**Comment by astagi** [comment]
YW

**Comment by 222dipa** [comment]
Hello and thanks for the fix! I still see the wrong color in the footer section. Can someone help me?

**Comment by mariantanase** [comment]
> Hello and thanks for the fix! I still see the wrong color in the footer section. Can someone help me?

Confirm!
I test this with changing the value for `$footer-top-background` variable in `colors_vars.scss`.
After compiling, it doesn't save the new value, it turns back with the initial value.

**Comment by astagi** [comment]
Thanks! Issue reopened

**Comment by zetareticoli** [comment]
@mariantanase @222dipa If you're trying to change the `footer` backgroud in `bootstrap-italia-comuni.scss` it's declared a specific variable:
```scss
$footer-comuni-bg-color: #202a2e;
```

**Comment by mariantanase** [comment]
Already did it but won't save it when build.
These are the steps:
1. On `bootstrap-italia-comuni-scss` changed the value to `$footer-comuni-bg-color: #006666`;
2. Save
3. > npm run build
4. The variable turns back to initial value:  `$footer-comuni-bg-color: #202a2e;`
5. Nothing changes

Whatever I edit, it is not saved. Even if you add a new line with a comment for example, it does not save it.
The variables take the initial values and the newly added rows are deleted.

**Comment by zetareticoli** [comment]
Can't riproduce your issue on my local env. 

Where's located the `bootstrap-italia-comuni-scss` you're trying to edit?

**Comment by mariantanase** [comment]
> Can't riproduce your issue on my local env.
> 
> Where's located the `bootstrap-italia-comuni-scss` you're trying to edit?

`bootstrap-italia-playground-main` > `bootstrap-italia` > `src` > `scss` > `bootstrap-italia-comuni.scss`

**Comment by mariantanase** [comment]
I'm back with news.

If I change the values on :
`bootstrap-italia-playground-main > node_modules > bootstrap-italia > src > scss > bootstrap-italia-comuni.scss`
The values are saved but not applied.

If I edit the values on:
`bootstrap-italia-playground-main > node_modules > bootstrap-italia > src > scss > utilities > colors_vars.scss`
The values are applied.

I've changed with my custom colors the following variables: **$footer-top-background**, **$footer-bottom-background**.
It works but these values (I mean from footer colors) should be calculated based on the custom main color in bootstrap-italia-custom.scss. I think...
